---
name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed
      
env:
  GH_TAG: ${{ github.event.workflow_run.head_branch }}

jobs  :
  test-job:
    name: Test Steps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: |
          echo '${{ toJSON(github) }}'
          echo ${{ github.event.workflow_run.head_branch }}
          echo ${{ github.event.workflow_run.head_sha }}
          echo ${{ github.event.workflow_run.status }}
          echo ${{ github.event.workflow_run.conclusion }}
          echo ${{ github.event.workflow_run.pull_requests }}
          echo ${{ github.event.workflow_run.repository.full_name }}
          echo ${{ github.event.workflow_run.env }}
          echo ${{ github.event.workflow_run.github.ref }}
      - run: git branch
      - run: env
      - run: echo "this is a tag :-)"
        if: startsWith(github.event.workflow_run.head_branch, 'refs/tags/')
